[compiler]
compiler_cmd = "{compiler_cmd}"
debug_args = [{debug_args}]
release_args = [{release_args}]

[package]
name = "{name}"
type = "{type}"
version = "{version}"
author = "{author}"
e-mail = "{e-mail}"
