/*
 * COCADA - COCADA Collection of Algorithms and DAta Structures
 *
 * Copyright (C) 2016  Paulo G S Fonseca
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 */

/**
 * @file cdmdtest.c
 * @author Paulo Fonseca
 * @ai ai-generated, Claude (Anthropic)
 */

#include <string.h>

#include "CuTest.h"
#include "cdfile.h"
#include "cdmd.h"
#include "cdsym.h"
#include "memdbg.h"
#include "new.h"


#define ASSERT_HAS(PAGE, TEXT) \
	CuAssert(tc, "page lacks: " TEXT, strstr(PAGE, TEXT) != NULL)
#define ASSERT_LACKS(PAGE, TEXT) \
	CuAssert(tc, "page has: " TEXT, strstr(PAGE, TEXT) == NULL)


static const char *SRC_A =
    "/**\n"
    " * @file a.h\n"
    " * @author A\n"
    " * @ai ai-generated, Claude (Anthropic)\n"
    " * @brief Module A.\n"
    " *\n"
    " * # Usage\n"
    " * Uses #b_func, #b_t.x, ::b_func, b.h and #nothing.\n"
    " */\n"
    "/**\n"
    " * @brief A point.\n"
    " */\n"
    "typedef struct {\n"
    "\tint x; /**< The x <b>coordinate</b> */\n"
    "\tint y;\n"
    "} point;\n"
    "/**\n"
    " * @brief Moves @p p into #point, if j<k and <id>.\n"
    " * @param @move p The point.\n"
    " * @return @move The copy.\n"
    " * @warning Careful\n"
    " * - really\n"
    " * @see b_func, b.h\n"
    " */\n"
    "point *take(point *p, int n);\n"
    "void undoc(void);\n"
    "#define TWICE(X) (2 * (X))\n";

static const char *SRC_B =
    "/**\n * @file b.h\n * @author B\n * @brief Module B.\n */\n"
    "/**\n * @brief B func.\n */\nvoid b_func(void);\n"
    "/**\n * @brief B type.\n */\ntypedef struct {\n\tint x; /**< The x */\n} b_t;\n";


void test_cdmd_page(CuTest *tc)
{
	memdbg_reset();
	cdfile *a = cdfile_new_from_str("lib/src/a.h", SRC_A, strlen(SRC_A));
	cdfile *b = cdfile_new_from_str("lib/src/sub/b.h", SRC_B, strlen(SRC_B));
	vec *files = vec_new(sizeof(cdfile *));
	vec_push_rawptr(files, a);
	vec_push_rawptr(files, b);
	cdsymtab *tab = cdsymtab_new(files);

	char *name = cdmd_page_name(a);
	CuAssertStrEquals(tc, "a.md", name);
	FREE(name);

	char *page = cdmd_page(a, tab);
	// header, navigation, description, contents
	ASSERT_HAS(page, "# a.h\n\nModule A.\n\n**Author:** A\n\n"
	           "**AI involvement:** [AI-generated, human-directed](ai-levels.md#ai-generated) "
	           "(Claude (Anthropic))\n\n"
	           "[Description](#description) · [Contents](#contents) · "
	           "[Back to module index](index.md#lib)\n\n## Description\n\n## Usage\n");
	ASSERT_HAS(page, "## Contents\n\n**Types and constants**\n\n- [point](#point): A point.\n\n"
	           "**Functions**\n\n- [take](#take): Moves `p` into [point](#point)");
	ASSERT_HAS(page, "- [undoc](#undoc): *undocumented*\n\n**Macros**\n\n- [TWICE](#twice): *undocumented*");
	ASSERT_HAS(page, "[Back to contents](#contents)\n\n## Functions\n\n### take");
	ASSERT_HAS(page, "---\n\nGenerated by [cocadoc](https://github.com/paguso/cocada) 0.1.0");
	// references
	ASSERT_HAS(page, "Uses [b_func](b.md#b_func), [b_t.x](b.md#b_t), [b_func](b.md#b_func), "
	           "[b.h](b.md) and `nothing`.");
	// sections, in order
	CuAssertTrue(tc, strstr(page, "## Types and constants") < strstr(page, "## Functions\n"));
	CuAssertTrue(tc, strstr(page, "## Functions\n") < strstr(page, "## Macros"));
	// struct with members
	ASSERT_HAS(page, "### point\n\n```c\ntypedef struct {\n\tint x;\n\tint y;\n} point;\n```");
	ASSERT_HAS(page, "- `x`: The x **coordinate**\n- `y`: *undocumented*");
	// function: @p, local link, escaping, params, moved return
	ASSERT_HAS(page, "Moves `p` into [point](#point), if j\\<k and \\<id>.");
	ASSERT_HAS(page, "- `p` **(moved)**: The point.\n- `n`: *undocumented*");
	ASSERT_HAS(page, "**Returns** (moved to the caller): The copy.");
	ASSERT_HAS(page, "> **Warning:** Careful\n> - really");
	ASSERT_HAS(page, "**See also:** [b_func](b.md#b_func), [b.h](b.md)");
	// undocumented function and macro
	ASSERT_HAS(page, "### undoc\n\n```c\nvoid undoc(void);\n```\n\n*Undocumented.*\n\n"
	           "[Back to contents](#contents)");
	// (an item with no comment at all just says so; no parameter list)
	ASSERT_HAS(page, "### TWICE\n\n```c\n#define TWICE(X)\n```\n\n*Undocumented.*");
	ASSERT_LACKS(page, "**Returns:** *undocumented*\n\n### TWICE"); // void: no return

	FREE(page);
	page = cdmd_page(b, tab);
	ASSERT_HAS(page, "[Back to module index](index.md#lib)");
	ASSERT_LACKS(page, "AI involvement"); // no @ai: human, no note
	FREE(page);

	char *index = cdmd_index(files, "X 1.0 API Reference");
	ASSERT_HAS(index, "# X 1.0 API Reference\n\n## lib\n\n- [a.h](a.md): Module A.\n"
	           "- sub/\n  - [b.h](b.md): Module B.\n");
	ASSERT_HAS(index, "[AI involvement levels](ai-levels.md)");
	FREE(index);

	char *levels = cdmd_ai_levels_page();
	ASSERT_HAS(levels, "# AI involvement levels\n");
	ASSERT_HAS(levels, "## ai-generated\n\n**AI-generated, human-directed.** Mostly or entirely");
	ASSERT_HAS(levels, "## human\n");
	ASSERT_HAS(levels, "Headers that declare no AI involvement are `human`");
	ASSERT_HAS(levels, "## ai-autonomous\n");
	FREE(levels);

	cdsymtab_free(tab);
	DESTROY_FLAT(files, vec);
	cdfile_free(a);
	cdfile_free(b);
	CuAssert(tc, "Memory leak.", memdbg_is_empty());
}


void test_cdmd_module_of(CuTest *tc)
{
	memdbg_reset();
	const char *cases[][3] = {
		{"libcocada/src/container/vec.h", "libcocada", "container/vec.h"},
		{"../x/libfoo/src/a.h", "libfoo", "a.h"},
		{"src/a.h", ".", "a.h"},
		{"some/dir/a.h", "some/dir", "a.h"},
		{"a.h", ".", "a.h"},
	};
	for (size_t i = 0; i < sizeof(cases) / sizeof(cases[0]); i++) {
		char *module, *rel;
		cdmd_module_of(cases[i][0], &module, &rel);
		CuAssertStrEquals(tc, cases[i][1], module);
		CuAssertStrEquals(tc, cases[i][2], rel);
		FREE(module);
		FREE(rel);
	}
	CuAssert(tc, "Memory leak.", memdbg_is_empty());
}


CuSuite *cdmd_get_test_suite()
{
	CuSuite *suite = CuSuiteNew("cdmd");
	SUITE_ADD_TEST(suite, test_cdmd_page);
	SUITE_ADD_TEST(suite, test_cdmd_module_of);
	return suite;
}
