################################################################################
# 
# COCADA - COcada COllection of Algorithms and DAta structures
# http://github.com/paguso/cocada
#
# (c) 2016- Paulo G. S. Fonseca 
#
################################################################################


# library identification and version
lib_name     := cocada
lib_major    := 0
lib_minor    := 1
lib_release  := 1

# library dependencies (only direct compilation dependencies)
lib_deps	 :=


include ../lib.mk