/*
 * COCADA - COCADA Collection of Algorithms and DAta Structures
 *
 * Copyright (C) 2016  Paulo G S Fonseca
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 */

#ifndef CDMACRO_H
#define CDMACRO_H

#include <stdbool.h>
#include <stddef.h>

#include "cddecl.h"
#include "cdfile.h"
#include "vec.h"

/**
 * @file cdmacro.h
 * @author Paulo Fonseca
 * @ai ai-generated, Claude (Anthropic)
 * @brief Macro-generated declarations (rule DC14).
 *
 * A small macro expander, just enough for the way COCADA generates typed
 * families of types and functions:
 *
 * ```c
 * #define DECL_VEC_PUSH( TYPE ) void vec_push_##TYPE(vec *v, TYPE val);
 * #define DECL_TYPED_VEC( TYPE , ...) DECL_VEC_NEW(TYPE) DECL_VEC_PUSH(TYPE) ...
 * XX_CORETYPES(DECL_TYPED_VEC)
 * ```
 *
 * It knows the function-like macros of all the documented headers (the
 * first definition of each), and expands each file-scope macro invocation
 * with parameter substitution, `__VA_ARGS__`, token pasting (`##`) and
 * rescanning. Stringizing (`#`), object-like macros and `#if` are not
 * handled.
 *
 * A **leaf generator** is a macro whose body declares something (rather
 * than only invoking other macros, like a **composite generator** or a
 * type list such as `XX_CORETYPES`). Each declaration of a leaf generator
 * makes a **family**: its expansions are the family's **instances**
 * (`vec_push_int`, `vec_push_double`, ...), and its **pattern** is the
 * declaration with the generator's parameters as placeholders
 * (`void vec_push_TYPE(vec *v, TYPE val);`).
 *
 * The doc comment of a family is the one above the `#define` of its
 * generator, if the generator declares a single type or function. A family
 * with a single instance may also be documented by a doc comment above the
 * invocation.
 */


/**
 * @brief A generated declaration.
 */
typedef struct {
	char *args;          /**< The arguments of the generator, e.g. "int" (heap) */
	cddecl *decl;        /**< The declaration (heap) */
} cdinstance;


/**
 * @brief A family of generated declarations.
 */
typedef struct {
	const cddecl *gen;       /**< The leaf generator (a macro) */
	const cdfile *gen_file;  /**< The file defining the generator */
	size_t index;            /**< Index of the declaration in the generator */
	const cddecl *pattern;   /**< The declaration with placeholders, or NULL */
	vec *instances;          /**< The instances (vec of #cdinstance) */
	vec *via;                /**< The invocations that generate them (vec of heap char *) */
	size_t line;             /**< Line of the first of these invocations */
	const cddecl *doc_decl;  /**< The declaration whose doc comment documents the family, or NULL */
} cdfamily;


/**
 * @brief A problem found while expanding macros.
 */
typedef struct {
	size_t line;         /**< Line of the invocation */
	char *msg;           /**< Message (heap) */
} cdmacrowarn;


/**
 * @brief Kinds of macros, as generators.
 */
typedef enum {
	CDG_NONE = 0,        /**< Not a function-like macro, or declares nothing */
	CDG_LEAF,            /**< Declares types or functions */
	CDG_COMPOSITE        /**< Only invokes other macros */
} cdgen_kind;


/**
 * @brief Macro table type (opaque).
 */
typedef struct _cdmacrotab cdmacrotab;


/**
 * @brief Builds the table of the function-like macros of a set of files.
 * @param files The files (vec of #cdfile *). They must outlive the table.
 * @return @move The table.
 */
cdmacrotab *cdmacrotab_new(const vec *files);


/**
 * @brief Destructor.
 * @param @move self The table.
 */
void cdmacrotab_free(cdmacrotab *self);


/**
 * @brief Finds the families generated by the macro invocations of a file.
 * @param self The macro table.
 * @param f The file.
 * @param warns Problems found are appended here (vec of #cdmacrowarn).
 * @return @move The families (vec of #cdfamily), in the order of their
 *         first invocation. Destroy with #cdfamily_vec_free.
 */
vec *cdmacro_families(const cdmacrotab *self, const cdfile *f, vec *warns);


/**
 * @brief Destroys a vector returned by #cdmacro_families.
 * @param @move families The vector.
 */
void cdfamily_vec_free(vec *families);


/**
 * @brief Destroys a vector of warnings.
 * @param @move warns The vector (vec of #cdmacrowarn).
 */
void cdmacrowarn_vec_free(vec *warns);


/**
 * @brief Classifies a macro as a generator.
 * @param self The macro table.
 * @param macro A macro declaration.
 * @param patterns If not NULL, set to the patterns of the declarations of a
 *        leaf generator (vec of #cddecl, owned by the table), or NULL.
 * @return The kind of generator.
 */
cdgen_kind cdmacro_generator(const cdmacrotab *self, const cddecl *macro,
                             const vec **patterns);


/**
 * @brief Tells whether a macro is invoked directly at file scope in some
 * file (e.g. `DECL_TRAIT(vec_iter, iter)`), rather than only by other
 * macros.
 * @param self The macro table.
 * @param name The macro name.
 * @return Whether it is.
 */
bool cdmacro_invoked(const cdmacrotab *self, const char *name);


/**
 * @brief Tells whether a name is used by macros: in the body of a macro, or
 * in the arguments of a file-scope invocation (e.g. `DECL_ARRAY` in
 * `XX_CORETYPES(DECL_ARRAY)`).
 * @param self The macro table.
 * @param name The name.
 * @return Whether it is.
 */
bool cdmacro_used_by_macros(const cdmacrotab *self, const char *name);


/**
 * @brief Returns the heading of a family: the name of its single instance,
 * or else of its pattern (e.g. "vec_push_TYPE").
 * @param fam The family.
 * @return The name.
 */
const char *cdfamily_name(const cdfamily *fam);

#endif
