/*
 * COCADA - COCADA Collection of Algorithms and DAta Structures
 *
 * Copyright (C) 2016  Paulo G S Fonseca
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 */

#ifndef CDMD_H
#define CDMD_H

#include "cdfile.h"
#include "cdsym.h"
#include "vec.h"

/**
 * @file cdmd.h
 * @author Paulo Fonseca
 * @brief Markdown documentation pages.
 *
 * Each header gets a page, named after it (`vec.h` → `vec.md`), with
 * these sections:
 *
 * 1. the module documentation (the file comment);
 * 2. types and constants;
 * 3. functions;
 * 4. macros.
 *
 * Each documented item has a `### name` heading, so that the anchors
 * generated by GitLab and GitHub (`vec.md#vec_new`) can be linked to.
 * References (`#name`, `#type.member`, `name.h`, `@see` entries) become
 * links when they resolve, and `@p name` becomes ``name``. Undocumented
 * items, parameters and return values are marked *undocumented*.
 *
 * An index page lists all modules, grouped by directory.
 */


/**
 * @brief Returns the name of the page of a file, e.g. "vec.md".
 * @param f The file.
 * @return @move The page name.
 */
char *cdmd_page_name(const cdfile *f);


/**
 * @brief Generates the documentation page of a file.
 * @param f The file.
 * @param tab The symbol table to resolve references with.
 * @return @move The page (Markdown).
 */
char *cdmd_page(const cdfile *f, const cdsymtab *tab);


/**
 * @brief Generates the index page.
 * @param files The files (vec of #cdfile *).
 * @return @move The page (Markdown).
 */
char *cdmd_index(const vec *files);

#endif
