################################################################################
# 
# COCADA - COcada COllection of Algorithms and DAta structures
# http://gitlab.com/paguso/cocada
#
# (c) 2016- Paulo G. S. Fonseca 
#
################################################################################


# library identification and version
LIB_NAME     := cocadastrproc
LIB_MAJOR    := 0
LIB_MINOR    := 1
LIB_RELEASE  := 1

DEP_LIBS		:= cocada

include ../lib.mk